### ISSUE TITLE
It doesn't display the chat messages

### ISSUE THREAD

**Issue by rom1504** [AlexKvazos/MinecraftChat#1]
Is that normal ?

**Comment by AlexKvazos** [comment]
What do you mean chat messages? I am aware that private messages are not displayed and I will be fixing that tonight. Public chat should be showing though.

**Comment by rom1504** [comment]
no it's not displaying any chat messages in the web interface (I'm testing with https://chat.alexkvazos.com/ and a vanilla 1.8 server)
Also I can't find anywhere in the code listening on the "chat" event ?

**Comment by roblabla** [comment]
It listens to the message event https://github.com/andrewrk/mineflayer/blob/master/doc/api.md#message-jsonmsg.

**Comment by AlexKvazos** [comment]
I am listening to the message event since the chat event only works with some servers. Are there any errors on your client or server console?

**Comment by rom1504** [comment]
oh right, well there aren't any § in vanilla 1.8 servers (https://github.com/AlexKvazos/MinecraftChat/blob/a2bda59bc4af864ee007a0eea63bdb12326aa8d6/app/server/bot/events/index.js#L58)

I guess you didn't test it with vanilla 1.8 servers ?

**Comment by AlexKvazos** [comment]
Ah I see.. I can modify the regex to use both the `§`and the `&`

**Comment by AlexKvazos** [comment]
Forgot to test with vanilla servers.. my bad!

**Comment by AlexKvazos** [comment]
But still, this shouldn't be a reason for the messages to not display at all on the buffer.

**Comment by rom1504** [comment]
vanilla servers send complicated json messages, for example : 
```
{ json: { translate: 'chat.type.text', with: [ [Object], 'test' ] },
  translate: 'chat.type.text',
  with: 
   [ { json: [Object],
       text: 'bot',
       bold: undefined,
       italic: undefined,
       underlined: undefined,
       strikethrough: undefined,
       obfuscated: undefined,
       color: undefined,
       clickEvent: [Object],
       hoverEvent: [Object] },
     'test' ],
  bold: undefined,
  italic: undefined,
  underlined: undefined,
  strikethrough: undefined,
  obfuscated: undefined,
  color: undefined }
```

**Comment by AlexKvazos** [comment]
Alright, I will be handling the multiple types of JSONs then. Thanks for reporting this to me. I never play on vanilla servers so it slipped when testing this out.

**Comment by AlexKvazos** [comment]
Starting at https://github.com/AlexKvazos/MinecraftChat/commit/80ed83f1ab2288dd0c68e43b04f4cbc60e93c3f8 the chat messages are now being shown. From what I see, the server responds with a JSON with what the client should render to the user. So implementing the entire vanilla commands will take some time.

Chat works for now though.

**Comment by rom1504** [comment]
I'm afraid it still doesn't work, I'm getting "[i] [MinecraftChat] Unknown data received from server. [Unsuported Server]" on a vanilla server.

You might be interested by the chat event on vanilla servers (and/or https://github.com/andrewrk/mineflayer/blob/master/lib/chat_message.js#L25)

**Comment by AlexKvazos** [comment]
That function looks interesting. I will try and implement it on the project itself. If I fail with that, I will just move to the chat event instead for vanilla servers.

**Comment by AlexKvazos** [comment]
The problem I am facing is that if I listen to the chat event, I get the following error when receiving messages from non-vanilla servers:

```
ReferenceError: matches is not defined
    at parseOldMessage (/Library/WebServer/Documents/AlexKvazos/MinecraftChat/node_modules/mineflayer/lib/plugins/chat.js:40:90)
    at parseJsonMessage7 (/Library/WebServer/Documents/AlexKvazos/MinecraftChat/node_modules/mineflayer/lib/plugins/chat.js:81:11)
    at parseJsonMessage (/Library/WebServer/Documents/AlexKvazos/MinecraftChat/node_modules/mineflayer/lib/plugins/chat.js:104:9)
    at Client.<anonymous> (/Library/WebServer/Documents/AlexKvazos/MinecraftChat/node_modules/mineflayer/lib/plugins/chat.js:118:5)
    at emitOne (events.js:77:13)
    at Client.emit (events.js:166:7)
    at afterParse (/Library/WebServer/Documents/AlexKvazos/MinecraftChat/node_modules/mineflayer/node_modules/minecraft-protocol/dist/client.js:97:10)
    at parseNewStylePacket (/Library/WebServer/Documents/AlexKvazos/MinecraftChat/node_modules/mineflayer/node_modules/minecraft-protocol/dist/protocol.js:1080:5)
    at prepareParse (/Library/WebServer/Documents/AlexKvazos/MinecraftChat/node_modules/mineflayer/node_modules/minecraft-protocol/dist/client.js:113:9)
    at Socket.<anonymous> (/Library/WebServer/Documents/AlexKvazos/MinecraftChat/node_modules/mineflayer/node_modules/minecraft-protocol/dist/client.js:124:5)
```

**Comment by rom1504** [comment]
@AlexKvazos I just fixed that, try and use the last mineflayer commit from master ?

**Comment by AlexKvazos** [comment]
Yeah it did get fixed. But this doesn't really solve this. I have to make a big switch that handles each of the different types of `message.translate`'s to display the message into the buffer. I will do all of this from the `message` event. Chat event doesn't give me the "You are now op" and the reponse of using /help or /list etc

**Comment by rom1504** [comment]
Okay, if you figure out a good way to handle many kind of messages format, it might be interesting to put that in mineflayer later. We're still trying to figure out what's the best way to handle all these chat format variations in mineflayer (see https://github.com/andrewrk/mineflayer/issues/175)

**Comment by AlexKvazos** [comment]
Well, my goal is to make it so that by just handling the `message` event, I can end with the string of the message regardless if it is from vanilla, spigot, or any other modded server. As of now, all the messages received from modded servers are being handled with no problem, and right now, I am doing the parse function that will handle vanilla messages.

Like this:
http://puu.sh/hvyhU/58b86423a7.png

**Comment by rom1504** [comment]
Now it indeed works, nice !
